Add proper logging from ETOS Test Runner.
eiffel-community/etos-test-runner pull request #39
Opened 2023-03-29 10:16 UTC by fredjn

### Applicable Issues
None

### Description of the Change
To increase observability of the ETOS Test Runner all relevant output is now done via python logging library, with support for suite ID (TERCC_ID) as a correlation identifier.

### Alternate Designs
None

### Benefits
Increased observability. We now get more regardign outputs from ETOS Test Runner as well as the possibility to send logs to remote log servers for further processing.

### Possible Drawbacks
None

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Fredrik Fristedt <<fredrik.fristedt@axis.com>>

2023-03-29 10:52 UTC, t-persson commented on src/etos_test_runner/__init__.py
> +"""ETOS environment provider module."""
What?

2023-03-29 20:10 UTC, fredjn commented
Getting black and pylint to play nice was seriously messed up. Not sure if there was some weird version discrepancy between my local tox runs and the github ones. I also had to add pylint disables on unchanged code which was a bit strange, how did the code get there without the disables in the first place? Could be a new verison of pylint perhaps.

2023-03-30 06:49 UTC, t-persson requested changes

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/etr.py
> +        except Exception as exc:  # pylint:disable=broad-exception-raised
```suggestion
        except Exception as exc:  # pylint:disable=broad-except
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/etr.py
> +                raise Exception(  # pylint:disable=broad-exception-raised
```suggestion
                raise AttributeError(
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/executor.py
> +            raise Exception(  # pylint:disable=broad-exception-raised
```suggestion
            raise RuntimeError(
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/iut_monitoring.py
> +    def __init__(self, iut, etos):
Add etos to docstring

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/testrunner.py
> +        except Exception as exception:  # pylint:disable=broad-exception-raised
```suggestion
        except Exception as exception:  # pylint:disable=broad-except
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/testrunner.py
> +                    raise Exception(  # pylint:disable=broad-exception-raised
```suggestion
                    raise TimeoutError(
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/workspace.py
> +            raise Exception("Workspace not created.")  # pylint:disable=broad-exception-raised
```suggestion
            raise FileNotFoundError("Workspace not created.")
```

2023-03-30 06:49 UTC, t-persson commented on src/etos_test_runner/lib/workspace.py
> +            raise Exception("Workspace not created.")  # pylint:disable=broad-exception-raised
```suggestion
            raise FileNotFoundError("Workspace not created.")
```

2023-03-30 06:49 UTC, t-persson commented on tests/lib/test_workspace.py
> +                    raise Exception(  # pylint:disable=broad-exception-raised
```suggestion
                    raise FileNotFoundError(
```

2023-03-30 06:49 UTC, t-persson commented on tests/lib/test_workspace.py
> +                    raise Exception(  # pylint:disable=broad-exception-raised
```suggestion
                    raise FileNotFoundError(
```

2023-03-30 10:09 UTC, fredjn commented on src/etos_test_runner/lib/iut_monitoring.py
> +    def __init__(self, iut, etos):
Fixed

2023-03-30 10:12 UTC, t-persson approved these changes

2023-03-30 10:23 UTC, andjoe-axis approved these changes

2023-03-30 12:09 UTC, merged